create table USERTABLE
(
	YCSB_KEY VARCHAR(255) PRIMARY KEY,
	FIELD0 VARCHAR, FIELD1 VARCHAR,
	FIELD2 VARCHAR, FIELD3 VARCHAR,
	FIELD4 VARCHAR, FIELD5 VARCHAR,
	FIELD6 VARCHAR, FIELD7 VARCHAR,
	FIELD8 VARCHAR, FIELD9 VARCHAR
);
