CREATE TABLE table1(a INTEGER NOT NULL, b INTEGER NOT NULL, c INTEGER NOT NULL);
CREATE TABLE table2(a INTEGER NOT NULL REFERENCES table1(a), b INTEGER NOT NULL, c INTEGER NOT NULL);
CREATE TABLE table3(a INTEGER NOT NULL, b INTEGER NOT NULL REFERENCES table1(b), c INTEGER NOT NULL REFERENCES table2(c));
