CREATE TABLE table1(a INTEGER PRIMARY KEY NOT NULL, b INTEGER NOT NULL, c INTEGER NOT NULL);
CREATE TABLE table2(a INTEGER NOT NULL REFERENCES table1(a), b INTEGER PRIMARY KEY NOT NULL, c INTEGER NOT NULL);
CREATE TABLE table3(a INTEGER NOT NULL REFERENCES table1(a), b INTEGER NOT NULL REFERENCES table2(b), c INTEGER PRIMARY KEY NOT NULL);
