package catalog.json;

import com.fasterxml.jackson.annotation.JsonCreator;

import java.util.Map;

/**
 * An instance is generated by parsing JSON. The required properties are:
 * - name
 * - default
 */
public class DataSourceSchema extends planner.DataSourceSchema {
    @JsonCreator
    public DataSourceSchema(Map<String, Object> properties) {
        super(properties);
    }
}
